{
  "zh": {
    "local": "zh",
    "desc": "多成中醫瀏覽器",
    "download": "下載",
    "betadownload": "測試版下載",
    "local_download": "本地下載",
    "android": "安卓版",
    "qr": "二維碼",
    "android_desc": "支持4.2以上手機和平板",
    "get_from_google_play": "從GOOGLE PLAY上下載",
    "ios": "IPhone/IPad",
    "ios_desc1": "或在Itunes/AppStore里搜索 “多成中医” 或 “duosuccess”",
    "ios_desc2": "iPad用户请在搜索时选择 “仅iPhone”, 下一个版本会有专门的iPad版",
    "chrome_plugin": "谷歌插件版,支持谷歌内核的浏览器",
    "chrome_plugin_desc": "支持Windows, Mac, Linux 下的谷歌浏览器 以及基于谷歌内核的, 如360极速, 猎豹...",
    "chrome": "Windows 谷歌瀏覽器",
    "chrome_desc": "無需安裝，解壓即用",
    "mac": "MAC版",
    "mac_desc": "OSX10.8开始，Safari浏览器无法播放midi, 可以用这个浏览器替代",
    "java": "JAVA手機版",
    "java_desc": "支持諾基亞等有JAVA功能的手機",
    "firefox": "Windows 火狐瀏覽器",
    "firefox_desc1": "请卸载之前的quicktime, 然后安装 包里的 qt_lite_410",
    "firefox_desc2": "在quicktime的 MIME 设置中，确保打开了Audio 下的 Midi",
    "firefox_desc3": "请用谷歌插件或者浏览器替代",
    "settings": "設置說明",
    "deprecated_msg": "以下版本即將停止維護",
    "ios_old": "IPHONE/IPAD 旧版",
    "ios_old_desc": "支持ios6.0以上手機和平板, 請使用Itunes/AppStore版本替代",
    "contact": "联系方式"
  },

  "en": {
    "local": "zh",
    "desc": "DuoSuccess TCM Browser",
    "download": "Download",
    "local_download": "Local Download",
    "android": "Android",
    "qr": "QR Code",
    "android_desc": "Supports Android 4.2+",
    "get_from_google_play": "Download from Google Play",
    "ios": "IPhone/IPad",
    "ios_desc1": "Or Search 'duosuccess' in Itunes/App Store",
    "ios_desc2": "For IPad, select “iPhone Only” in App Store.",
    "chrome_plugin": "Chrome Extension",
    "chrome_plugin_desc": "Support Chrome under Windows, Mac, Linux",
    "chrome": "Windows Chrome Browser",
    "chrome_desc": "Portable version, unzip and launch",
    "mac": "OSX version",
    "mac_desc": "For OSX10.8+, which stopped midi support.",
    "java": "JAVA ME version",
    "java_desc": "Supports J2ME mobile devices",
    "firefox": "Windows FireFox",
    "firefox_desc1": "Please uninstall current quicktime, then install qt_lite_410 in package",
    "firefox_desc2": "Make sure you select MIDI under Quicktime's MIME.",
    "firefox_desc3": "Deprecated, Please use Chrome instead.",
    "settings": "Settings",
    "deprecated_msg": "Below browsers will be removed soon",
    "ios_old": "IPHONE/IPAD OLD",
    "ios_old_desc": "Support ios6.0+, Please use Itunes/AppStore version",
    "contact": "Contact"
  }
}
